name: Laravel testing with PostgreSQL
on:
    - push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: |
                    source /etc/lsb-release
                    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1CE2AFD36DBCCA00
                    sudo echo "deb https://repos.loraserver.io/${DISTRIB_ID,,} ${DISTRIB_CODENAME} testing" | sudo tee /etc/apt/sources.list.d/loraserver.list
                    sudo apt-get update 
            -   name: Setup PHP with pgsql
                uses: shivammathur/setup-php@2.10.0
                with:
                    php-version: '7.4'
                    extensions: curl, pgsql, pdo_pgsql
                    tools: phpunit
            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-composer-${{ hashFiles('composer.json') }}
            -   name: Composer (php-actions)
                uses: php-actions/composer@v5
            -   name: Install front-end dependencies
                run: |
                  npm install
                  npm run dev
            -   name: Install composer dependencies
                run: |
                    composer install --no-scripts
            -   name: Run Testsuits
                run: $GITHUB_WORKSPACE/vendor/bin/phpunit tests/Feature --verbose