name: PHP CodeCoverage from CodeClimate
on:
    - push
jobs:
    build:
        runs-on: ubuntu-latest
        container: node:10.18-jessie
        services:
        postgres:
            image: postgres
            env:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: test-php-lvl3
            ports:
            -   5432:5432
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup PHP with xdebug
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    tools: phpunit
                    coverage: xdebug
            -   name: Composer (php-actions)
                uses: php-actions/composer@v5
            -   name: Install front-end dependencies
                run: |
                  npm install
                  npm run dev
            -   name: Install composer dependencies
                run: |
                    composer install --no-scripts
            -   name: Run Testsuits
                run: $GITHUB_WORKSPACE/vendor/bin/phpunit tests/Feature