name: Laravel testing with PostgreSQL
on:
    - push
jobs:
    build:
        runs-on: ubuntu-20.04
        services:
            postgres:
                image: postgres:12.6
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test-php-lvl3
                ports:
                -   5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v2
                with:
                    node-version: '14'
            -   name: Setup PHP with pgsql
                uses: shivammathur/setup-php@2.10.0
                with:
                    php-version: '7.4'
                    extensions: curl, pgsql, pdo_pgsql
                    tools: phpunit
            -   name: Composer (php-actions)
                uses: php-actions/composer@v5
            -   name: Connect to SQLite
                run: make setup
            -   name: Code Climate Coverage and running Testsuits
                env:
                    CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
                run: |
                    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                    chmod +x ./cc-test-reporter
                    ./cc-test-reporter before-build
                    $GITHUB_WORKSPACE/vendor/bin/phpunit tests/Feature --coverage-clover clover.xml
                    ls -al
                    ./cc-test-reporter after-build --coverage-input-type clover
